### ISSUE TITLE
Prepare for inclusion in the list of awesome lists

### ISSUE THREAD

**Issue by koppor** [dzharii/awesome-elasticsearch#29]
I saw an attempt to include this list in the [curated list of awesome lists](https://github.com/sindresorhus/awesome) at https://github.com/sindresorhus/awesome/pull/1004.

Although all elements include a description, it does not fully follow the requirements by sindresorhus. Would it be possible to update the list according to the requirements stated at https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md?

**Comment by dzharii** [comment]
Dear @koppor, 

The [rule](https://github.com/dzharii/awesome-elasticsearch#contributing) almost from the day one of this list says:

>> Do not even try to add this repo to any awesome-awesome-* lists

![image](https://user-images.githubusercontent.com/36020/30469408-062b1f5a-99a5-11e7-8f41-057bc7307ae0.png)

With all my (truly) respect what sindresorhus and his team does, I don't want to participate in that list, mainly because of the requirements they have. 

I appreciate your effort and good intentions, but, please don't go any further with this. 

Thank you,
@dzharii
