### ISSUE TITLE
List of managed providers

### ISSUE THREAD

**Issue by brauliobo** [dzharii/awesome-elasticsearch#38]
Hi, I'm missing a list of managed providers like cloud.elastic.io, AWS Elasticsearch, etc. I'm interested in managed solution that supports plugins.

**Comment by dzharii** [comment]
Hi @brauliobo 
Quick google search gave me this link: 
https://www.slant.co/topics/170/~best-hosted-elasticsearch-services hope this could help in your search

Stackoverflow could be a better place to ask this question, since the issues here do not receive a lot of traffic. (I am closing this issue)
