### ISSUE TITLE
Elasticsearch

### ISSUE THREAD

**Issue by d1motion** [dzharii/awesome-elasticsearch#51]
Hello,
I need to extract my data logs to visualization on kibana\elasticsearch. I can see my data logs from the log section of kibana, but I don't know how to extract specific data from it.

Any help would be great.

Thank you.

**Comment by dzharii** [comment]
Hi @d1motion  Stackoverflow.com or https://discuss.elastic.co/ would be a better place to ask a question. 

When you would post a question on the resources above, I would suggest to add more details about the shape of your data, what would you like to achieve, add screenshots if necessary and provide an example of the current state and the desired outcome. So that the people could understand the problem and help faster.

Logstash is widely used for reading, filtering, parsing and saving the data to elasticsearch as well as to other sinks: like flat files or SQL Databases. 
https://www.elastic.co/products/logstash

Kibana supports manual Export to JSON/CSV

www.elastic.co has free video training  and webinars (you need to register)
